package com.sebone.deliveringsmiles.interfaces;
import com.sebone.deliveringsmiles.dataclasses.*;
import java.time.*;
import java.util.List;
/**
 * Interface Name DriverRegistration
 * Objective -Payout is the interface where we declare all the methods regarding payouts,
 *  like what is the amount of the money the driver got from a particular order, 
 *  what is the monthly payout generated by the driver and all the things. 
 * @author Ayush Tamrakar
 *
 */
public interface Payout {
	public PayoutData payoutByOrder (int orderId , int driverId);
	public List<PayoutData> payoutOfTheDays(OrderStatus orderStaus, int driverId, LocalDate startDate,LocalDate endDate );
	public List<PayoutData> totalPayout( int driverId );
}